### PR TITLE
Add test for attoparsec-text-lazy

### PR DESCRIPTION
**Pull request by expipiplus1**
The dense version is catastrophically slow, the sparse version is faster

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks!

**Comment by jamesdbrock** [comment]
Hey @expipiplus1 I think this PR was missing the file `AttoparsecTextLazy.hs`? Would you please give me the file, if you still have it? I would like to add it to the benchmarks. You don't even have to make a PR, just paste the file in a comment here.

**Comment by jamesdbrock** [comment]
@expipiplus1  I guessed that the `AttoparsecTextLazy.hs` file contains

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Attoparsec.Text.Lazy
import Replace.Attoparsec.Text.Lazy
import Data.Text.Lazy.IO as T

main :: IO ()
main = T.getContents
    >>= streamEditT (string "x") (return . const "oo")
    >>= T.putStr
```

but when I run that, it seems to give worse relative benchmarks than what you reported here. https://github.com/jamesdbrock/replace-attoparsec/pull/4#issuecomment-888805909

Did I guess right or did the `AttoparsecTextLazy.hs` file contain something else?

**Comment by expipiplus1** [comment]
my version was 

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Attoparsec.Text.Lazy
import Replace.Attoparsec.Text.Lazy
import Data.Text.Lazy.IO as T

main :: IO ()
main = T.getContents
    >>= pure . streamEdit (string "x") (const "oo")
    >>= T.putStr
```

(The difference is in the location of `pure`/`return`).

Does this make any difference?

**Comment by jamesdbrock** [comment]
Oh no lol, your version with `streamEdit` instead of `streamEditT` is 2× faster in the __dense__ case @expipiplus1 . Well this is why we benchmark. Predicting the performance of Haskell programs is hard.

#### `streamEditT (string "x") (return . const "oo")`

| Program                                           | dense *ms*  | sparse *ms* |
| :---                                              |      ---: |     ---:  |
| [`Replace.Attoparsec.ByteString.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-ByteString.html#v:streamEdit) | 2648.31 | 248.93 |
| [`Replace.Attoparsec.Text.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-Text.html#v:streamEdit) | 3567.92 | 304.54 |
| [`Replace.Attoparsec.Text.Lazy.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-Text-Lazy.html#v:streamEdit) | 5725.92 | 235.38 |

#### `pure . streamEdit (string "x") (const "oo")`

| Program                                           | dense *ms*  | sparse *ms* |
| :---                                              |      ---: |     ---:  |
| [`Replace.Attoparsec.ByteString.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-ByteString.html#v:streamEdit) | 2684.26 | 256.71 |
| [`Replace.Attoparsec.Text.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-Text.html#v:streamEdit) | 3587.53 | 310.88 |
| [`Replace.Attoparsec.Text.Lazy.streamEdit`](https://hackage.haskell.org/package/replace-attoparsec/docs/Replace-Attoparsec-Text-Lazy.html#v:streamEdit) | 2771.04 | 336.74 |

**Comment by expipiplus1** [comment]
Interesting!

I can't think at the moment, but I would be interested to know the
specifics why if you do investigate

**Pull request merged**
